Mission09_dbcampbe/Controllers/PurchaseController.cs
using Microsoft.AspNetCore.Mvc;
using Mission09_dbcampbe.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission09_dbcampbe.Controllers
{
    public class PurchaseController : Controller
    {
        private IPurchaseRepository repo { get; set; }
        private Basket basket { get; set; }
        public PurchaseController (IPurchaseRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }


        //Pull up the checkout.cshtml page and passing a new purchase object
        [HttpGet]
        public IActionResult Checkout()
        {
            return View(new Purchase());
        }
        
        [HttpPost]
        public IActionResult Checkout(Purchase purchase)
        {
            //Check to see if the basket is empty if they try to make a purchase
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry your basket is empty!");
            }

            //turn the basket item objects into purchase line objects and send them to a confirmation page after purchase
            if (ModelState.IsValid)
            {
                purchase.Lines = basket.Items.ToArray();
                repo.SavePurchase(purchase);
                basket.ClearBasket();

                return RedirectToPage("/PurchaseCompleted");
            }
            else
            {
                return View();
            }
        }
    }
}

Mission09_dbcampbe/Pages/Cart.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Mission09_dbcampbe.Infrastructure;
using Mission09_dbcampbe.Models;

namespace Mission09_dbcampbe.Pages
{
    public class CartModel : PageModel
    {
        private IBookRepository repo { get; set; }

        public CartModel (IBookRepository temp, Basket b)
        {
            repo = temp;
            basket = b; 
        }

        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            //Send them back to the url they came from and if there isn't one send them to the home page
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            basket.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(int bookId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Book.BookId == bookId).Book);

            return RedirectToPage( new {ReturnUrl = returnUrl});
        }
    }
}

Mission09_dbcampbe/Pages/PurchaseCompleted.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Mission09_dbcampbe.Pages
{
    public class PurchaseCompletedModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Mission09_dbcampbe/Pages/Cart.cshtml
@page
@model Mission09_dbcampbe.Pages.CartModel
@{
}

<h2>Your basket</h2>

@*Display the shopping cart in a table*@
@*Adding the table-hover was one of the extra bootstrap things I did*@
<table class="table table-bordered table-striped table-hover">
    @*Adding the table-dark was the other extra bootstrap thing I did*@
    <thead class="table-dark">
        <tr>
            <th>Item</th>
            <th>Quantity</th>
            <th>Cost</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var i in Model.basket.Items)
        {
            <tr>
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>@i.Book.Price.ToString("c")</td>
                <td>@((i.Quantity * i.Book.Price).ToString("c"))</td>

                @* Remove button *@
                <td class="text-center">
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="bookId" value="@i.Book.BookId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    </form>
                </td>

            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            @*Dynamically create the total based on what they have added to their basket*@
            <td>@Model.basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>

</table>

<div>
    @*Return the shopper to the previous page they were on*@
    <a class="btn btn-primary" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" asp-controller="Purchase" asp-action="Checkout">Checkout</a>
</div>

Mission09_dbcampbe/Pages/PurchaseCompleted.cshtml
@page
@model Mission09_dbcampbe.Pages.PurchaseCompletedModel
@{
}
<div class="text-center">
    <h2>Thanks for purchasing</h2>
    <a class="btn btn-primary" asp-controller="Home">Return Home</a>
</div>

Mission09_dbcampbe/Pages/_CartLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>

    <div class="bg-dark text-white p-2">Book STORE</div>

    <div class="m-1 p-1">
        @RenderBody()
    </div>
</body>
</html>