Mission09_dbcampbe/Components/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mission09_dbcampbe.Models;

namespace Mission09_dbcampbe.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        //Create ViewComponent for the cart based on the basket
        private Basket basket;  
        public CartSummaryViewComponent(Basket b)
        {
            basket = b;
        }
        public IViewComponentResult Invoke()
        {
            return View(basket);
        }

    }
}

Mission09_dbcampbe/Views/Shared/BookSummary.cshtml
@{
}

@model Book

<div class="card card-outline-primary m-1 p-1">
    <div class="bg-faded p-1">
        <h4>
            @Model.Title
            <span class="badge badge-pill badge-primary bg-dark" style="float:right">
                <small>@Model.Price.ToString("c")</small>
            </span>
        </h4>
    </div>
    @*Print out the fields for each Book*@
    <div class="card-text p-1">
        <ul>
            <li>Author: @Model.Author</li>
            <li>Publisher: @Model.Publisher</li>
            <li>Isbn: @Model.Isbn</li>
            <li>Classification: @Model.Classification</li>
            <li>Category: @Model.Category</li>
            <li>PageCount: @Model.PageCount</li>
        </ul>
    </div>

    <form method="post" asp-page="/Cart">

        @*Pass the BookId and the current url without the user having to see it*@
        <input type="hidden" asp-for="@Model.BookId" />
        <input type="hidden" name="returnURL" value="@ViewContext.HttpContext.Request.PathAndQuery()"/>

        <span class="card-text">
            <button type="submit" class="btn btn-success btn-sm float-end">Add to Cart</button>
        </span>
    </form>
</div>

Mission09_dbcampbe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @*Import bootstrap*@
    <link href="/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0-1/css/all.min.css" 
          integrity="sha512-ZYg+hQvLlM0W9C3P6vTpes5LmJ66G2EsroxDNzwD6qiulckldb29eD9I672HL2X+LH5nRhY1sQqZLJGB+aUUPg==" 
          crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">BOOK STORE</div>
                <div class="col-6 text-right">
                    @* Use the view component for the cart summary *@
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>
    <div class="row m-1 p-1">
        <div id="categories" class="col-3">
            <vc:types-views-component></vc:types-views-component>
        </div>
        <div class="col-9">
            @RenderBody()
        </div>
    </div>
</body>
</html>